# Use the official Python image as the base image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the entire project directory to the container
COPY . .

# Install required packages
RUN pip install --no-cache-dir nba_api pandas

# Run the update_data.py script when the container starts
CMD ["python", "update_data.py"]